export interface Image {
    id: number, 
    title: string, 
    thumbnail: any, 
    date_start: number, 
    date_end: number, 
    date_display: string, 
    artist_display: string, 
    place_of_origin: string, 
    description: string, 
    dimensions: string, 
    medium_display: string, 
    publication_history: string, 
    exhibition_history: string, 
    provenance_text: string, 
    gallery_title: string, 
    gallery_id: number, 
    artwork_type_title: string, 
    artwork_type_id: number, 
    department_title: string, 
    department_id: string, 
    category_ids: string[], 
    category_titles: string[], 
    term_titles: string[], 
    style_titles: string[], 
    classification_titles: string[], 
    subject_titles: string[], 
    material_titles: string[], 
    technique_titles: string[], 
    image_id: string, 
    
}
